<a href="https://colab.research.google.com/github/LavenaD/Medical-Test-Summarisation/blob/main/TrainModel_V2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1. Install the libraries required to import the model from Hugging face**

In [2]:
!pip install torch transformers datasets accelerate rouge-score evaluate pandas

Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (2.10.0+cu128)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.13.0)
Collecting rouge-score
  Downloading rouge_score-0.1.2.tar.gz (17 kB)
  Preparing metadata (setup.py) ... done
Collecting evaluate
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch) (3.29.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2025.3.0)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch) (1.5.3)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.11.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from rouge-score) (1.4.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (from rouge-score) (3.9.1)
Requirement already satisfied: six>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from rouge-score) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.13.5)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.24.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2026.4.22)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch) (3.0.3)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk->rouge-score) (8.3.3)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk->rouge-score) (1.5.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.23.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (4.13.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (0.16.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.1.2)
Downloading evaluate-0.4.6-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 5.7 MB/s eta 0:00:00
Building wheels for collected packages: rouge-score
  Building wheel for rouge-score (setup.py) ... done
  Created wheel for rouge-score: filename=rouge_score-0.1.2-py3-none-any.whl size=24934 sha256=0db01a4d216a4ad5467e8926676c6df07b10213510cc520839b1db21eeb0ed0a
  Stored in directory: /root/.cache/pip/wheels/85/9d/af/01feefbe7d55ef5468796f0c68225b6788e85d9d0a281e7a70
Successfully built rouge-score
Installing collected packages: rouge-score, evaluate
Successfully installed evaluate-0.4.6 rouge-score-0.1.2

**2. Read the data after the data is cleaned and stored in a csv file**

In [3]:
import pandas as pd
df = pd.read_csv('/content/sample_data/output_20260424114330_Train_Full.csv')
df.head()

,id,findings,labels
0,3997,"Heart size within normal limits. Small, nodula...","No acute findings, no evidence for active TB."
1,3996,The lungs are clear. Heart size is normal. No ...,Clear lungs. No acute cardiopulmonary abnormal...
2,3995,The cardiomediastinal silhouette and pulmonary...,1. Interval resolution of bibasilar airspace d...
3,3994,Similar mild cardiomegaly. Of the pulmonary va...,Mild cardiomegaly with XXXX of early failure.
4,3993,The heart is mildly enlarged. Left hemidiaphra...,Borderline cardiomegaly without acute disease.

**3. Include additional text in the findings column which will summarize the text.**

In [4]:
df["findings"] = "Summarize this medical condition: " + df["findings"]

In [5]:
df.head()
print(df['findings'][0])
print(len(df['findings'][0]))

Summarize this medical condition: Heart size within normal limits. Small, nodular opacity in the right upper lobe. This does not look like an acute infiltrate, and more XXXX represents a granuloma. No pneumothorax or effusions.
227

**4. Download the model from huggingface**

In [6]:
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

model_name = "google/flan-t5-small"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json: 0.00B [00:00, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/308M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/190 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

**5. Use Lora to train the model**

In [7]:
import torchao
print(f"Installed torchao version: {torchao.__version__}")

Installed torchao version: 0.10.0

In [8]:
!pip uninstall torchao -y

Found existing installation: torchao 0.10.0
Uninstalling torchao-0.10.0:
  Successfully uninstalled torchao-0.10.0

In [9]:
import sys
!{sys.executable} -m pip install torchao>=0.16.0
from peft import LoraConfig, get_peft_model

lora_config = LoraConfig(
    r=14,
    lora_alpha=16,
    target_modules=["q", "v"],
    lora_dropout=0.1,
    bias="none",
    task_type="SEQ_2_SEQ_LM"
)

model = get_peft_model(model, lora_config)

**6. Set the training arguments**

In [10]:
from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="./medical_model",
    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,
    num_train_epochs=4,
    learning_rate=8.8e-5,
    logging_steps=100,
    eval_strategy="epoch",
    save_strategy="epoch"
)

**7. Split the data into train and test**

In [11]:
from transformers import Trainer
from datasets import Dataset
from sklearn.model_selection import train_test_split

# Convert pandas DataFrame to Hugging Face Dataset
dataset = Dataset.from_pandas(df)

# Split the dataset into train and test sets using the Dataset's own split method
split_datasets = dataset.train_test_split(test_size=0.1, seed=42)
train_dataset = split_datasets["train"]
test_dataset = split_datasets["test"]

**8. Tokenize the data**

In [12]:
# Define the tokenization function
def tokenize_function(examples):
  # return tokenizer(examples["findings"],
  #                  text_target=examples["labels"],
  #                  truncation=True)
  return tokenizer(
        [str(f) for f in examples["findings"]],
        text_target=[str(l) for l in examples["labels"]],
        truncation=True
    )

# Apply tokenization to the datasets
tokenized_train_dataset = train_dataset.map(tokenize_function, batched=True)
tokenized_test_dataset = test_dataset.map(tokenize_function, batched=True)

# Remove the original text columns as they are no longer needed
tokenized_train_dataset = tokenized_train_dataset.remove_columns(["id", "findings"])
tokenized_test_dataset = tokenized_test_dataset.remove_columns(["id", "findings"])

# Make sure the 'labels' column is correctly set for training
tokenized_train_dataset.set_format("torch", columns=["input_ids", "attention_mask", "labels"])
tokenized_test_dataset.set_format("torch", columns=["input_ids", "attention_mask", "labels"])

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_train_dataset,
    eval_dataset=tokenized_test_dataset
)

trainer.train()

Map:   0%|          | 0/1525 [00:00<?, ? examples/s]

Map:   0%|          | 0/170 [00:00<?, ? examples/s]

TrainOutput(global_step=6100, training_loss=8.575549486504226, metrics={'train_runtime': 674.1469, 'train_samples_per_second': 9.048, 'train_steps_per_second': 9.048, 'total_flos': 153159329292288.0, 'train_loss': 8.575549486504226, 'epoch': 4.0})

**9. Save the model**

In [13]:
import os
output_dir = "/content/medical_model/compressed-artifacts-g5/"
os.makedirs(output_dir, exist_ok=True)

model.save_pretrained("/content/medical_model/compressed-artifacts-g5/medical_summarizer_peft")
tokenizer.save_pretrained("/content/medical_model/compressed-artifacts-g5/medical_summarizer_peft")

('/content/medical_model/compressed-artifacts-g5/medical_summarizer_peft/tokenizer_config.json',
 '/content/medical_model/compressed-artifacts-g5/medical_summarizer_peft/tokenizer.json')

In [14]:
from transformers import AutoModelForSeq2SeqLM

base_model = AutoModelForSeq2SeqLM.from_pretrained(
    "google/flan-t5-small"
)

Loading weights:   0%|          | 0/190 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning

In [15]:
from peft import PeftModel

print(type(model))

<class 'peft.peft_model.PeftModelForSeq2SeqLM'>

In [16]:
from peft import PeftModel

model = PeftModel.from_pretrained(
    base_model,
    "/content/medical_model/compressed-artifacts-g5/medical_summarizer_peft"
)

In [17]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained(
    "/content/medical_model/compressed-artifacts-g5/medical_summarizer_peft"
)

**10. Run Predictions**

In [18]:
import pandas as pd
import torch
import evaluate
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
from peft import PeftModel

model_path = "/content/medical_model/compressed-artifacts-g5/medical_summarizer_peft"

# load base model
base_model = AutoModelForSeq2SeqLM.from_pretrained("google/flan-t5-small")

# attach LoRA adapter
model = PeftModel.from_pretrained(base_model, model_path)

# tokenizer
tokenizer = AutoTokenizer.from_pretrained(model_path)

device = torch.device("cpu")
model.to(device)

# load data
test_df = pd.read_csv("/content/sample_data/output_20260424115121_validation.csv")

inputs = test_df["findings"].tolist()
references = test_df["labels"].tolist()

# predict
predictions = []

# inputs = inputs[0:10]

for text in inputs:

    text = ''' Summarize this medical condition: ''' + text

    tokens = tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        max_length=256
    ).to(device)

    output = model.generate(
        **tokens,
        max_length=256,
        num_beams=5
    )

    pred = tokenizer.decode(
        output[0],
        skip_special_tokens=True
    )

    predictions.append(pred)

print(predictions)
print(inputs)
print(references)

Loading weights:   0%|          | 0/190 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning

['No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary abnormality.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardi

In [19]:
!pip install evaluate rouge_score

Requirement already satisfied: evaluate in /usr/local/lib/python3.12/dist-packages (0.4.6)
Requirement already satisfied: rouge_score in /usr/local/lib/python3.12/dist-packages (0.1.2)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.0.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.0.2)
Requirement already satisfied: dill in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.2.2)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.32.4)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from evaluate) (3.6.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.70.16)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (1.11.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from evaluate) (26.1)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from rouge_score) (1.4.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (from rouge_score) (3.9.1)
Requirement already satisfied: six>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from rouge_score) (1.17.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (3.29.0)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (18.1.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (3.13.5)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (0.24.2)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2026.4.22)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk->rouge_score) (8.3.3)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk->rouge_score) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk->rouge_score) (2025.11.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2026.1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.23.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (4.13.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (0.16.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.7.0->evaluate) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.7.0->evaluate) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.7.0->evaluate) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.7.0->evaluate) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.7.0->evaluate) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.7.0->evaluate) (0.1.2)

In [20]:
import evaluate

rouge = evaluate.load("rouge")

results = rouge.compute(
    predictions=predictions,
    references=references
)

print(results)

Downloading builder script: 0.00B [00:00, ?B/s]

{'rouge1': np.float64(0.4628855976564419), 'rouge2': np.float64(0.3112153235106317), 'rougeL': np.float64(0.4619403533062294), 'rougeLsum': np.float64(0.4624617903033378)}

In [21]:
print(predictions)

['No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary abnormality.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardiopulmonary disease.', 'No acute cardi

In [22]:
import zipfile
import os
from google.colab import files

folder_to_compress = "/content/medical_model/compressed-artifacts-g5/medical_summarizer_peft"
output_zip_name = "medical_summarizer_model_g5.zip"

# Create a ZipFile object
with zipfile.ZipFile(output_zip_name, 'w', zipfile.ZIP_DEFLATED) as zipf:
    for root, dirs, files_in_folder in os.walk(folder_to_compress):
        for file in files_in_folder:
            file_path = os.path.join(root, file)
            # Add file to zip, preserving directory structure relative to folder_to_compress
            zipf.write(file_path, os.path.relpath(file_path, folder_to_compress))

print(f"'{folder_to_compress}' successfully compressed to '{output_zip_name}'")

# Download the zip file
files.download(output_zip_name)

'/content/medical_model/compressed-artifacts-g5/medical_summarizer_peft' successfully compressed to 'medical_summarizer_model_g5.zip'